brave/qa-resources

- braveautogen.py
Updated labels and assignees in the change-log generator for browser-laptop
> updated labels and assignees

- wikitemplate
> Replace notification test URL's scheme to https

- wikitemplate-android
Added updates to Data section for Android Template only per https://github.com/brave/qa-resources/issues/18
> updated Data section of Android Template

- braveautogen-chromium-upgrade.py
- wikitemplate-cr-upgrade
> Add chromium tests generator

- wikitemplate-cr-upgrade.md
Fix #22 and added a space above `## Installer` which fixes the spacing between the OS Checklist and `## Installer` when generating reports.
> Adding test case for WebSockets into wikitemplate-cr-upgrade.md

- wikitemplate-cr-upgrade.md
- wikitemplate.md
Added Upgrade test for preview build
Added CR template with data tests
Modified flash test on Wikitemplate
Closes #25
> Update wikitemplate files

- braveautogen-chromium-upgrade.py
- braveautogen-ios.py
- braveautogen.py
> reassign test runs

- wikitemplate-cr-upgrade.md
- wikitemplate.md
> Add media ledger tests

- braveautogen-pre-release-only.py
Closes #33
Script generates pre-release only checklist for all platforms
> add pre release only script

- braveautogen-chromium-upgrade.py
- braveautogen-pre-release-only.py
- braveautogen.py
- wikitemplate-android.md
- wikitemplate-cr-upgrade.md
- wikitemplate-ios.md
- wikitemplate.md
> Remove Windows ia32 tests from test run generator

- wikitemplate-cr-upgrade.md
> Add bravery test to chromium upgrade template

- braveautogen-pre-release-only.py
> Updates issue name

- wikitemplate-cr-upgrade.md
> Add enabling extensions test case

- wikitemplate-cr-upgrade.md
- wikitemplate.md
> adds cursor into pointer test case

- wikitemplate-android.md
- wikitemplate-cr-upgrade.md
- wikitemplate-ios.md
- wikitemplate.md
Closes #55 
@diracdeltas Is the fix available on iOS and Android as well or is it only for laptop?
> Add WebRTC fingerprint test

- wikitemplate.md
> Add sync test back to testsheet

- wikitemplate.md
> adding tab discarding

- wikitemplate.md
> adding lazy loading manual cases

- wikitemplate.md
> adding manual passes for password managers

- wikitemplate.md
> Fix Mozilla Geolocation

- bc-wikitemplate.md
Fixes #91 
This is same as #92  which was reverted and re added.
> Update template for b-c tests

- wikitemplate.md
> Add GPU Verification tests

- brave_testrun_generator.py
Fixes https://github.com/brave/qa-resources/issues/111
> Fix milestones

- wikitemplate.md
Fixes  #119
source: https://docs.google.com/document/d/1qp8mW9YfmgH4NsP_nZrOjejCwiMzld36jWv25M4GiOc/edit
> Adding more tests for components/extensions

- wikitemplate.md
> Remove muon import test case

- brave_testrun_generator.py
> Fix iOS assignees

- wikitemplate-crypto.md
Fixes https://github.com/brave/qa-resources/issues/159
> Add recovery test for Crypto wallet

- wikitemplate-crypto.md
Fixes https://github.com/brave/qa-resources/issues/162
> Add responsive screen test

- wikitemplate-goupdate.md
> Fix 169: Add process and test plan for go-update

- brave_testrun_generator.py
- wikitemplate-android.md
Fixes #161 
@btlechowski @kjozwiak please review Sync tests. Also updated the test run wiki to be more condensed 
@LaurenWags please review test script. Should be able to grab and create test runs for Android-Core
> Fix Android core test script and wikitemplate

- wikitemplate.md
Updating our manual passes as they're pretty stale. This is the first pass. They'll be several other changes to area's like `Sync`, `Rewards` and `Import` which will be done sometime this week.
> Updating QA Manual Passes

- wikitemplate-minorCRbump.md
Going to use the same cases we've using via https://github.com/brave/qa-resources/blob/master/wikitemplate.md#upgrade which have been updated via https://github.com/brave/qa-resources/pull/178.
> Changing/Updating our "Update" cases for minor CR bumps

- wikitemplate.md
Fix #151
Fix #114
Fix #166 
Updates include:
- minor adjustment in `Brave Ads` section for #166 
- major changes in `Rewards` section for #151 and #114
> Rewards section updates

- brave_testrun_generator.py
Fixes https://github.com/brave/qa-resources/issues/181
> Add OS labels when generating test runs

- wikitemplate-android.md
> Add site settings test for branding

- wikitemplate.md
Added Brave's .onion website into our passes.
> Added Brave .onion address

- wikitemplate-crypto.md
> Update Crypto test sheet

- wikitemplate.md
> Adding Google Exception cases

- wikitemplate-tor.md
> Fix 197: /tmp doesn't work on all platforms

- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
@kjozwiak r?
Also fixed a new-line warning and a trailing whitespace char.
> Add HBO Max Widevine tests

- wikitemplate-tor.md
> Fix #230: Update tor test-plan to check for notarization and static binary

- wikitemplate-tor.md
Resolves #232
Add `Open in Tor` test cases into https://github.com/brave/qa-resources/blob/master/wikitemplate-tor.md so it's checked when QA runs through Tor component updates.
> Add new Tor cases

- wikitemplate-android.md
- wikitemplate-minorCRbumpAndroid.md
- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
> Adds startup checks for Brave endpoints

- .github/ISSUE_TEMPLATE/qaResourceOther.md
Editing the `Other` template. Changing from `Random` --> `Other`
> Fixing Other template

- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
https://github.com/brave/qa-resources/issues/243#issue-822535761
> Adding reward endpoint checks for opted out users

- wikitemplate.md
> Update context-menu item tests for element blocking

- wikitemplate.md
quick/easy r?  @kjozwiak thanks!
> Fix issue 271; s/New Tor Identity/New Tor Connection

- wikitemplate-android.md
- wikitemplate-minorCRbumpAndroid.md
Fix #281
Added ephemeral storage tests provided by @pes10k to the Android full and reduced manual passes.
> Add ephemeral storage test case

- wikitemplate-android.md
> Add IPFS,ENS,UD tests

- wikitemplate.md
> Add Hardware Wallet test for CR bumps

- wikitemplate-android.md
> Add tabgroups tests

- wikitemplate-android.md
- wikitemplate-minorCRbumpAndroid.md
Apologies; my ATOM editor saw fit to make those other whitespace changes - should be fine, just unexpected :-)
> Change minimum BAT to 15, from 25; fixes #306.

- wikitemplate-ios.md
> Add missing Brave Shields & Privacy menu item

- wikitemplate-ios.md
> Replace one brianbondy.com instance with blizzard.com

- wikitemplate-ios.md
> s/pin/passcode to match the UI term

- wikitemplate-IPFS.md
@srirambv literally a drop-and-replace; should be good to go, but scrutinize 👍
> Update to newer, more-complete IPFS template

- wikitemplate.md
> Fix "Trackers & ads blocked" word order

- wikitemplate-android.md
- wikitemplate-ios.md
> Update iOS template

- wikitemplate-android.md
- wikitemplate.md
Fixes https://github.com/brave/qa-resources/issues/338
> Fix wording of one fingerprinting test

- wikitemplate-macOS-arm64.md
Fix #351
Updated `universal` --> `arm64`
Updated app sizes
> Update macOS arm64 test run template

- wikitemplate-IPFS.md
Fixes https://github.com/brave/qa-resources/issues/353
@kjozwiak @srirambv r?
> Fix a few typos and clarify a tiny bit

- wikitemplate-IPFS.md
Fixes issue #355
@kjozwiak @srirambv r?
> Update to latest Cloudflare IPFS gateway link

- wikitemplate-IPFS.md
Fixes #359.
@kjozwiak @srirambv r?
Looks like this, now, with these changes:
> Add seed-profile section to IPFS test run.

- wikitemplate.md
Fixes issue #370
r? @kjozwiak @LaurenWags
> Update Brave .onion URL to V3

- wikitemplate.md
Fixes issue #373
r? @srirambv @kjozwiak (I'm assuming we want this as an additional check, but am not 100% sure)
> Add Brave Search .onion URL

- wikitemplate-ios.md
Cleans up some of the iOS template a bit.
> Fixes issue #386

- wikitemplate-tor-Linux.md
- wikitemplate-tor-Windows.md
- wikitemplate-tor-macOS(Intel).md
- wikitemplate-tor-macOS(arm64).md
- wikitemplate-tor.md
> Fix #397: update V2 Tor links to V3

- wikitemplate-android.md
Threw to the wind in our Slack channel for reviewers; r?
Fixes https://github.com/brave/qa-resources/issues/399
> Fix #399: Update 15 BAT to 2 BAT, per Uphold

- brave_testrun_generator.py
- wikitemplate-ReducedAndroid.md
- wikitemplate-ReducedDesktop.md
Fix #401
- Created wikitemplate-ReducedDesktop.md
- Created wikitemplate-ReducedAndroid.md
- Updated wikitemplate-minorCRbumpDesktop.md
- Updated wikitemplate-minorCRbumpAndroid.md
- Updated brave_testrun_generator.py to use wikitemplate-ReducedDesktop.md and wikitemplate-ReducedAndroid.md
> Separate CR bump and reduced passes

- wikitemplate-IPFS.md
@srirambv @lidel @spylogsster r?
(Also, sorry, couldn't resist a spot of cleanup by removing a couple platform-specific media filetypes.)
> Fix #406: add public-gateway list to IPFS run

- wikitemplate-IPFS.md
@lidel @spylogsster @srirambv r?
> Fix #408 - replace broken ipns://brave.crypto with ipns://brad.crypto

- wikitemplate-IPFS.md
> Fix #411: update `Open in IPFS` label to `IPFS`

- wikitemplate-IPFS.md
@MadhaviSeelam @kjozwiak @Uni-verse r?
cc @spylogsster @lidel
> Fix #421: change Use a local node to Use a Brave local IPFS node

- brave_testrun_generator.py
Fix #415
Removed Android x86 test run generation from test run generator
> Remove Android x86 manual passes from test run generator

- wikitemplate-ReducedDesktop.md
- wikitemplate.md
Fix #432
Made updates based on suggestions from previous review
> Additional Rewards test case wording updates

- wikitemplate.md
Remove obsolete fingerprint test; make it so.
> Fix issue #447

- wikitemplate-IPFS.md
Remove unnecessary test for unimplemented feature.
@srirambv @Uni-verse @kjozwiak r?
> Fix issue #473

- wikitemplate-ReducedDesktop.md
- wikitemplate.md
> Remove test for unsupported `Restore` feature in Rewards

- WikiTemplate/Tor/wikitemplate-tor-Windows.md
- WikiTemplate/Tor/wikitemplate-tor-macOS(Intel).md
- WikiTemplate/Tor/wikitemplate-tor-macOS(arm64).md
Fix #456
Made updates as described in issue
> Update Windows and macOS (Intel and M1) Tor templates

- brave_testrun_generator.py
> Update IPFS labels and action name

- WikiTemplate/Android/wikitemplate-ReducedAndroid.md
- WikiTemplate/Android/wikitemplate-android.md
- WikiTemplate/Android/wikitemplate-minorCRbumpAndroid.md
- WikiTemplate/Desktop/Reduced/wikitemplate-ReducedDesktop.md
- WikiTemplate/Desktop/wikitemplate.md
> Remove references to wallet in rewards context

- WikiTemplate/Desktop/Major_CR_Bump/wikitemplate-majorChromiumBumpUpgrades.md
Fix #493
Made updates as described in https://github.com/brave/qa-resources/issues/493#issue-1448174579 and https://github.com/brave/qa-resources/issues/493#issuecomment-1343389464
> Update Major CR bump template to reflect component changes

- WikiTemplate/Desktop/wikitemplate.md
Fix #499
Removed PDF test case link since the page referenced no longer works
> Remove broken PDF test case

- WikiTemplate/Desktop/Major_CR_Bump/wikitemplate-majorChromiumBumpUpgrades.md
- WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbump-macOS-arm64.md
- WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbumpDesktop.md
- WikiTemplate/Desktop/Reduced/wikitemplate-ReducedDesktop.md
- WikiTemplate/Desktop/wikitemplate-macOS-arm64.md
- WikiTemplate/Desktop/wikitemplate.md
Fix #503
Added tests as suggested in https://github.com/brave/qa-resources/issues/503#issuecomment-1420031840.
> Add checks for adblock lists and filters

- WikiTemplate/Desktop/Major_CR_Bump/wikitemplate-majorChromiumBumpUpgrades.md
> Fix spelling of "chromium" in major-CR-bump run

- WikiTemplate/Tor/wikitemplate-tor-macOS(Intel).md
Fixes https://github.com/brave/qa-resources/issues/531
@kjozwiak @LaurenWags r?
> Add Sonoma to macOS-x64/Intel template

- WikiTemplate/Desktop/wikitemplate.md
Fixes https://github.com/brave/qa-resources/issues/537
> Swap 1Password in for LastPass

- WikiTemplate/Desktop/wikitemplate.md
Fixes https://github.com/brave/qa-resources/issues/548
@MadhaviSeelam @LaurenWags @kjozwiak
> Make Firefox import test match reality

- WikiTemplate/Desktop/wikitemplate.md
Fix #522
- Updated Rewards test cases
> Update Desktop Rewards test cases

- WikiTemplate/Desktop/wikitemplate.md
Fix #547
Removed deprecated speedreader component reference
> Removed Speedreader component from test sheet on Desktop

- WikiTemplate/Desktop/wikitemplate.md
Fix #560
Added additional case as requested by @GeetaSarvadnya
> Added additional Rewards case

- WikiTemplate/Desktop/wikitemplate.md
Fix #535
Added "Query Filter" tests to full manual passes
> Added Query Filter tests to full manual pass

- README.md
> Update readme file to current changes

- WikiTemplate/Android/wikitemplate-android.md
> Removed and updated one rewards test

- WikiTemplate/Desktop/wikitemplate.md
Fix https://github.com/brave/qa-resources/issues/579
> Update cookies cases from `Social-media blocking settings` section

- README.md
fixes https://github.com/brave/qa-resources/issues/592
> Update README for tokens

- WikiTemplate/Desktop/wikitemplate.md
> Updated IPFS test case on desktop manual pass

- WikiTemplate/iOS/wikitemplate-ios.md
Resolves https://github.com/brave/qa-resources/issues/565
Resolves https://github.com/brave/qa-resources/issues/611
Resolves https://github.com/brave/qa-resources/issues/613
Resolves https://github.com/brave/qa-resources/issues/614
> Adding several new checks/cases for `iOS`

- WikiTemplate/Desktop/wikitemplate.md
Resolves https://github.com/brave/qa-resources/issues/616
> Removing WebTorrent cases from manual passes

- README.md
- brave_testrun_generator.py
Resolves https://github.com/brave/qa-resources/issues/621
> Remove `IPFS` from test script

- brave_testrun_generator.py
Resolves https://github.com/brave/qa-resources/issues/625
> Fix `iOS` repo issue
