brave/qa-resources

- wikitemplate-cr-upgrade.md
- wikitemplate.md
Fix #28 and added keyboard shortcut test cases into both the `wikitemplate-cr-upgrade.md` and `wikitemplate.md` templates.
> Adding keyboard shortcut test cases

- wikitemplate-cr-upgrade.md
- wikitemplate.md
> Added crash,fingerprint and fixed geo location test

- wikitemplate-android.md
- wikitemplate-cr-upgrade.md
- wikitemplate-ios.md
- wikitemplate.md
Fixes #49 & #51 
Added WebRTC check link for Android
Moved not implemented items on Android to a separate heading
Moved PDF test to download on Android
Added Browser lock test for iOS
Replaced safe browsing link for iOS and Android
Replaced reader mode link for iOS
> Update test sheet v1

- wikitemplate.md
Fixes: #43
Removed unnecessary `.` from template and fixed autofill test case
> Fix autofill test case

- wikitemplate.md
> adding test cases for ledger table with a large list of entries

- wikitemplate-ios.md
> Update iOS test sheet

- wikitemplate.md
> Remove obsolete FTP test

- wikitemplate.md
> Add rewards test to test plan

- changelog.py
> Add changelog generator

- brave_testrun_generator.py
- wikitemplate-ios.md
> Fix iOS template and test run

- brave_testrun_generator.py
> Fix labels for closed items

- wikitemplate-android.md
- wikitemplate-ios.md
- wikitemplate.md
Fixes #110 
Update Fixes #117  as well
> Add sync tests for all platforms

- wikitemplate-android.md
> Update Android test sheet

- brave_testrun_generator.py
- wikitemplate-hotfix.md
Fixes #125 
* Added condensed test run for HF 
* Only need to add the version number for Ads tests once test run is generated. 
* Added check for excluding `Per-release item` if there are no open issues - Verified against `Dupe` milestone manually.
> Add HF test to test run

- wikitemplate.md
Fixes: #120 
Fixes: #127 
* Added social media buttons check to the regression list 
* Added ads test to the regression list
> Add ads/social-media test cases

- brave_testrun_generator.py
Fixes  #130
Fixed issue listing for each device type
x86  test sheet will  excluded for all ads/rewards issues going forward
ARM/x86 will exclude tablet specific tests now
ARM Tab will exclude phone specific tests now
> Fix Android test run

- brave_testrun_generator.py
Fixes: #132 
* Format python code as per pycodestyle
- `pycodestyle ./brave_testrun_generator.py` returns no complains
- Ran `python3 brave_testrun_generator.py --test true` and checked able to generate test runs for all platforms
> Fix python styling as per pycodestyle

- brave_testrun_generator.py
- wikitemplate-ios.md
Fixes : #137
* Removed redundant iPhone tests 
* Added specific test runs for iPad/iPhone/iPhone X
* Fixed spelling/grammer mistakes in iOS template file
> Remove redundant test run and update template

- brave_testrun_generator.py
> Fix iPhone X issue list

- brave_testrun_generator.py
- wikitemplate-crypto.md
Fixes: #146 
* Created new Crypto Wallet template file
* Added new section for generating crypto wallet tests independent of desktop releases
Screenshots:
* Working as expected tested on existing milestone(closed) `Ethereum Remote Client 1.0.10`
* Works fine when no `Ethereum` milestone is available
> Add crypto template and tests

- wikitemplate-android.md
Fixes: #134
* Added Rewards/Ads test 
* Fixed spelling and grammatical mistakes
> Add rewards test

- wikitemplate-ios.md
Fixes  #154
- Added Rewards and WebAuthn tests
- Fixed a few other items (see changes)
> Add Rewards/WebAuthn tests

- wikitemplate-tor.md
Fixes: https://github.com/brave/qa-resources/issues/165
> Guidelines for testing updates to tor client

- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
Fix #201
1. Changed brianbondy.com --> blizzard.com per discussion with @kjozwiak 
2. Removed part about allowing scripts from URL bar, this was removed in 1.19.x via https://github.com/brave/brave-browser/issues/199
3. Added upgrade case for AC to confirm it does not get re-enabled on upgrade
> Minor updates to test sheet

- wikitemplate.md
* substituted https://torrent.ubuntu.com/ for the 404'ing https://webtorrent.io/torrents link
* spelling fixes, including pedantic s/login/log in (noun vs. verb), s/Github/GitHub, etc.
* upper-cased Shields, so it stands out as the feature/proper noun I think it is
* hyphenation for things like `right-click`
* added folder/directory names for removed and automatically re-populated components
* disambiguated Chrome Web Store in the heading
And a few more; should be minor, but please nit-pick away!
> Minor tweaks for clarification

- wikitemplate-macOS-arm64.md
Fix #220
Added wikitemplate-macOS-arm64.md for macOS arm64/M1 testing.
> Add macOS arm64/M1 specific test pass template

- wikitemplate-android.md
- wikitemplate.md
I tried for parity, but Android doesn't have the scheme handler that we do on desktop, and perfect is the enemy of good.
I'll squash commits before merging, once approved.
r? @kjozwiak @diracdeltas @srirambv?
> Add DNS leak tests for desktop and Android; fixes issue #235

- brave_testrun_generator.py
- wikitemplate-IPFS.md
Closes #322 
Closes #323 
PR contains:
* New wiki template file for IPFS based on https://github.com/brave/brave-browser/issues/16669
* Update Test script to generate test runs for IPFS releases
* Some minor tweaks to make the console output look nice
> Add IPFS WikiTemplate & update testscript

- wikitemplate-android.md
- wikitemplate-majorChromiumBumpUpgrades
- wikitemplate-minorCRbumpAndroid.md
- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
Fixes https://github.com/brave/qa-resources/issues/390 👍 Also prevents https://github.com/brave/brave-browser/issues/20501 from happening again.
> Fixes Tor link & Outbound connections

- wikitemplate-IPFS.md
(They reference Cloudflare's IPFS gateway, rather than the default public gateway, `dweb.link`.)
@spylogsster @srirambv @lidel r?
> Fix #416: Gateway links for Wikipedia are wrong

- wikitemplate-ReducedDesktop.md
- wikitemplate-macOS-arm64.md
- wikitemplate-majorChromiumBumpUpgrades
- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
Fix #429
Removed references to "wallet" in rewards context on desktop test templates
> Remove references to wallet for Brave Rewards on desktop templates

- wikitemplate-tor-Linux.md
- wikitemplate-tor-Windows.md
- wikitemplate-tor-macOS(Intel).md
- wikitemplate-tor-macOS(arm64).md
- wikitemplate-tor.md
Fix #427
Changed wording of `Open in Tor` to be `Tor` to reflect change made with https://github.com/brave/brave-browser/issues/18923.
> Update wording for Tor button in URL bar

- brave_testrun_generator.py
- wikitemplate-minorCRbump-macOS-arm64.md
Fix #436
Made macOS arm64/M1 mentioned in https://bravesoftware.slack.com/archives/GAA4017R7/p1649120940013549:
- added a new template file, `wikitemplate-minorCRbump-macOS-arm64.md`, which is a reduced set of the original macOS arm64 tests from `wikitemplate-macOS-arm64.md`
- updated `brave_testrun_generator.py` to use this new template
- confirmed my changes locally by running `brave_testrun_generator.py` in `test` mode
> Reduce macOS arm64 template for CR bump only

- wikitemplate-android.md
Updating upgrade cases to they're easier to run through for new employees/contributors or employees who would like to help but never ran through a manual pass.
> Upgrade changes to manual pass

- wikitemplate-ReducedDesktop.md
- wikitemplate-macOS-arm64.md
- wikitemplate-minorCRbump-macOS-arm64.md
- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
Fix #440
Updated various templates to accommodate macOS universal builds
> Update test run templates to accomodate macOS universal builds

- wikitemplate-ReducedDesktop.md
- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
Fix #450
Added TLS pinning check to:
- `wikitemplate.md` (full desktop manual pass, run for each major Chromium bump)
- `wikitemplate-minorCRbumpDesktop.md` (reduced desktop manual pass, run for each minor Chromium bump that is done on Release Channel)
- `wikitemplate-ReducedDesktop.md` (reduced desktop manual pass, run for hot fixes that do not contain a minor Chromium bump)
> Update Desktop test runs to include TLS Pinning check

- wikitemplate-ReducedDesktop.md
- wikitemplate-minorCRbumpDesktop.md
- wikitemplate.md
This is only valid once https://github.com/brave/security/issues/990 has been merged, but it will ensure that we don't accidentally regress on https://github.com/brave/brave-browser/issues/24454.
Note that it's related to what was done in #452. That other one was to check that Brave pins are enforced, this new one is to check that Google pins are **not** enforced.
> Update Desktop tests to expand TLS Pinning check

- wikitemplate-IPFS.md
`IPFS Gateway` is currently just an `Enabled`/`Disabled` toggle.
Remove its test.
> Remove unnecessary test; fixes issue #466

- wikitemplate-IPFS.md
Add another test -- `vitalik.eth` -- to the ENS portion of the IPFS manual run.
Fixes https://github.com/brave/qa-resources/issues/477.
> Fixes issue 477: Add another test for ENS domains

- wikitemplate.md
Adds a test for `vitalik.eth` via ENS + IPFS.  Fixes https://github.com/brave/qa-resources/issues/475.
As simple as I can make it - we can expand the IPFS + ENS/Unstoppable Domains coverage in further pulls, if need-be.
> Fixes issue 475: Add a test for IPFS-backed ENS domain (vitalik.eth)

- WikiTemplate/Android/wikitemplate-ReducedAndroid.md
- WikiTemplate/Android/wikitemplate-android.md
LMK if you want me to include the `- [ ] Verify user still able to connect to existing Uphold account via panel even when balance is < 2 BAT` test too
> Fixes #489: remove outdated Uphold tests on Android

- WikiTemplate/Android/wikitemplate-ReducedAndroid.md
- WikiTemplate/Android/wikitemplate-android.md
- WikiTemplate/Desktop/Reduced/wikitemplate-ReducedDesktop.md
- WikiTemplate/Desktop/wikitemplate.md
Fix #495
Updated rewards test cases on desktop and android for full and reduced manual passes (no changes to update testing for Rewards made at this time)
> Refresh Rewards Test Cases

- WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbump-macOS-arm64.md
- WikiTemplate/Desktop/wikitemplate-macOS-arm64.md
Fix #488
Removed references to x64 builds on the arm64 manual passes for macOS.
> Remove references to macOS x64 builds in macOS arm64 manual passes

- WikiTemplate/Desktop/wikitemplate.md
Change from `Allow Google login buttons on third-party sites` to `Allow use of third-party cookies for legacy Google Sign-In`
@kjozwiak @LaurenWags @srirambv r?
> Fix issue #514 - update pref wording

- WikiTemplate/Desktop/wikitemplate.md
Fixes #516
@LaurenWags hopefully I'm correct, and my proposed change is what was intended?
> Fix typo in `Create custom filters` heading

- WikiTemplate/iOS/wikitemplate-ios.md
Revamped the test cases in the wikitemplate for iOS to conform to our current testing. It turned out to be quite cumbersome. Open to suggestions on how to trim it down but we should be testing all of these items. We could always create a reduced version for smaller releases. Some sections can be removed (iPad Navigation)
I closed off https://github.com/brave/qa-resources/pull/501 since it was stale.
> Update ios tests

- brave_testrun_generator.py
Fix #542
Per the above issue, 
- commented out the ability to generate the "Reduced" set of test cases for both Desktop and Android as we no longer have designated mid-cycle maintenance releases where these reduced cases were used. Now, we will have the full manual pass (to be run for each major chromium bump version) and a set of basic checks which will be run for each hotfix (whether it contains a minor chromium bump or not).
- updated the generation of manual passes to now create a Linux test run for the basic checks
> Update test run generator

- WikiTemplate/Android/wikitemplate-android.md
Fix #563
Added "Query Filter" tests per https://github.com/brave/qa-resources/issues/563#issuecomment-1839731230.
> Add Query Filter tests to Android manual pass

- WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbump-macOS-x64.md
- WikiTemplate/Desktop/Minor_CR_Bump/wikitemplate-minorCRbumpDesktop.md
- WikiTemplate/Desktop/wikitemplate-macOS-x64.md
- WikiTemplate/Desktop/wikitemplate.md
- brave_testrun_generator.py
Fix #539
Changes made:
- Under `wikitemplate-minorCRbumpDesktop.md`
- changed `x64` to `arm64` references
- Added `wikitemplate-minorCRbump-macOS-x64.md`
- Under `wikitemplate.md`
- changed `x64` to `arm64` references
- Added `wikitemplate-macOS-x64.md`
- Updated `brave_testrun_generator.py`
Note: did not remove the following files, will keep for a bit and remove later:
- `wikitemplate-minorCRbump-macos-arm64-md`
- `wikiteamplate-macOS-arm64.md`
> Update desktop manual passes for macOS

- WikiTemplate/Desktop/wikitemplate.md
Fix #594
Added Manifest V2 Extension checks to full desktop manual pass per discussions under https://bravesoftware.slack.com/archives/C2J3NA3L7/p1723575334463169
> Add Manifest V2 checks to full desktop manual pass template

- brave_testrun_generator.py
Fix #603
Fix error:
```
Traceback (most recent call last):
File "brave_testrun_generator.py", line 933, in <module>
laptop_testruns(sorted(bc_milestone.keys())[0])
File "brave_testrun_generator.py", line 144, in laptop_testruns
bc_repo.create_issue(title=macTitle,
NameError: name 'macTitle' is not defined
```
Line 136 was updated but line 144 was not, PR updates line 144.
> Fix test run generator for full manual passes
